#!/bin/bash
#
#Skript arvutab sisestatud arvu numbrite summa koos seletava tekstiga
#
#skript algab
#
echo "Sisesta suvaline täisarv: "
read arv
#Summale väärtus
summa=0
while [$arv -ne 0]
do
#jäägi leidmine ja 10ga jagamine
jaak=$((arv % 10))
#lisatakse summasse
summa=$(($summa + $jaak))
#väljatab ülejäänud arvud
arv=$(($arv / 10))
done
echo "Arvu summa on $summa"
