#!/bin/bash
#
#Skript, mis vastavalt numbri sisestamisele ütleb millise kuuga on tegu
#
#skript algab
echo -n "Sisesta kuu number (1-12): "
read number
case $number in
	"1") echo "Jaanuar";;
	"2") echo "Veebruar";;
	"3") echo "Märts";;
	"4") echo "Aprill";;
	"5") echo "Mai";;
	"6") echo "Juuni";;
	"7") echo "Juuli";;
	"8") echo "August";;
	"9") echo "September";;
	"10") echo "Oktoober";;
	"11") echo "November";;
	"12") echo "Detsember";;
	*) echo "Sisesta number 1 ja 12 vahel"
esac
