#!/bin/bash
#
#
#kolmnurga pindala arvutamine
#
#skript algab
#
echo -n "Sisesta külje A väärtus:"
read  A
echo -n "Sisesta külje B väärtus:"
read B
echo -n "Sisesta külje C väärtus:"
read C
#järgmine rida leiab poole ümbermõõdust
P=$(bc <<< "scale=2;($A+$B+$C)/2")
a=$(($A))
c=$(($C))
#Leian heroni valemi abil kolmnurga pindala
S=$(bc <<< "scale=2; sqrt(($P-$A)*($P-$B)*($P-$C)*$P)")
#Väljastan  valemis kasutatud arvud
echo "A = $A"
echo "B = $B"
echo "C = $C"
echo "S = $S"
#
#skript lõppeb
#

