#!/bin/bash
#
#Reiilt tagasituleku päeva väljaselgitamine
#
#Skript algab
#Päevade numrilised väärtused
echo "Pyhapaev -0, Emaspaev-1, Teisipaev-2, Kolmapaev-3, Neljapaev-4, Reede-5, Laupaev-6"
#
echo -n "Siesta kodust lahkumise paeva nr:"
read reisi_algus
#sisesta reisi kestvus
echo -n "Sisesta reisi kestvus:"
read kestvus
#
#leian nädalate arvu
nadalad=`echo "$kestvus/7"|bc`
#leian reisi lõpp-päeva
loppkuupaev=`echo "$kestvus - $nadalad * 7" |bc`
#reisi lõpp-päeva number ei tohi olla suurem kui nr 6
paevanr=`echo "$reisi_algus + $loppkuupaev - (($reisi_algus + $loppkuupaev)/7)*7"|bc`
echo "Tagasi jouad paeval nr $paevanr"
#
#Skripti lõpp
